version: '4'

services:
  postgres:
    image: 'postgres:15'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_DB=TestShop'

  app:
      build: ./
      container_name: 'java_app'
      ports:
        - "8080:8080"
